// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Route_EF_S03_DataBase_First.Entitites
{
    public partial class SalesByCategoryResult
    {
        public string ProductName { get; set; }
        public decimal? TotalPurchase { get; set; }

    }
}
